// <auto-generated />
namespace Remont.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class OrderStatusId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderStatusId));
        
        string IMigrationMetadata.Id
        {
            get { return "201411111924013_OrderStatusId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
