// <auto-generated />
namespace Remont.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class StorageToRow1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StorageToRow1));
        
        string IMigrationMetadata.Id
        {
            get { return "201411181645251_StorageToRow1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
